# -*- coding: utf-8 -*-
"""AILab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZDg9qWOX_Fxu64H1hW82zVeoUi35E7A
"""

import seaborn as sns

tips = sns.load_dataset('tips')

tips.head()

sns.boxplot(tips['total_bill'])

tips.describe()

sns.boxplot(x='sex',y='total_bill',data=tips)

sns.boxplot(x='day',y='total_bill',hue='sex',data=tips)

sns.boxplot(x='day',y='total_bill',hue='sex',data=tips,palette='husl')

sns.boxplot(x='day',y='total_bill',hue='smoker',data=tips)

sns.boxplot(x='day',y='total_bill',hue='time',data=tips)

sns.boxplot(x='sex',y='total_bill',hue='time',data=tips)

sns.boxplot(x='day',y='total_bill', order=['Sun','Sat','Fri','Thur'],data=tips)

sns.boxplot(x='sex',y='tip',hue='time',data=tips)

sns.boxplot(x='sex',y='tip',data=tips)



"""Benefits of a Boxplot
Easy way to see the distribution of data
Tells about skewness of data
Can identify outliers
Compare two categories of data
"""